### ISSUE TITLE
As a user, I want to be able to customize all the category labels of the character sheet

### ISSUE THREAD

**Issue by roypenrod-ohn** [fariapp/fari#101]
## 🚩 Is your feature request related to a problem? Please describe

No, this is a request for a new feature.

## ✅ Describe the solution you'd like

FATE is a very flexible game.

One of the most common changes in FATE is to change the SKILLS to something else, like APPROACHES from FATE Accelerated.

Some other settings use terms like PROFESSIONS instead of SKILLS.

When I choose a Custom Character Sheet, I would like to click the section title SKILLS and change the text to what I need.

## 📄 Additional context

Here's a screenshot for a character from a "Hunters of Alexandria" one-shot I'm working on at the moment:

![edit-skills-example](https://user-images.githubusercontent.com/56047533/89620461-46ced000-d855-11ea-8331-ac6fb4e425a9.png)

**Comment by RPDeshaies** [comment]
Hey!

This is a good idea and I agree that it can be pretty handy to have.

I think it should not be too hard to do considering that mostly everything in the character sheet is already super customizable.

I'll push that even further and make every label in the character sheet (Aspects, Stunts & Extras, Stress, Skills) overridable.

I'll see if I have the time to do it before releasing v3 or otherwise it will go in a minor release shortly after that.

**Comment by RPDeshaies** [comment]
Had a bit of time this afternoon and managed to make that work :D 
Will be released in V3 #89 

Related commit: https://github.com/fariapp/fari/pull/89/commits/d5880912e2dced0bd7ff3428245b47f05e16706a

**Comment by roypenrod-ohn** [comment]
Just tested this on the Fari v3.0.0 Prerelease and it worked for me.  Thanks!
