### ISSUE TITLE
As a user, I want to be easily able to know if my browser supports Fari and it's Web RTC features

### ISSUE THREAD

**Issue by technicalpickles** [fariapp/fari#111]
## 🚩 Describe the bug

I am just testing things out, and I went to https://fari.app/ and clicked "Star Online Game". I just see a spinner indefinitely. I can see an error in web developer tools complaining about unsupported browser.

## 🔢 Steps to reproduce

1. Use Firefox
1. Go to https://fari.app
2. Click on 'Start Online Game'
4. See spinner
5. Open Web Developer Tools
6. See error in console

## 🟢 Expected behavior

Be able to play a game 😁  Or at least be told to use a different browser.

## 🔴 Actual behavior

...

## 💅 Screenshots

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/159/92416168-2c289900-f12a-11ea-9946-7d22594dbe36.png">

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/159/92416175-3b0f4b80-f12a-11ea-87f6-5e2395676c51.png">

## 🖥 Desktop or Smartphone

- OS: macOS
- Browser: Firefox
- Device: MacBook Pro

## 📄 Additional context

...

**Comment by RPDeshaies** [comment]
Hey, thanks for opening this issue.

I just tried loading the app on my mac mini (Catalina) + a fresh firefox I just installed and I can't seem to reproduce the issue.

Which version of firefox are you using? I'm on `80.0.1 (64 bits)`

![image](https://user-images.githubusercontent.com/6224111/92416389-3dbe7080-f12b-11ea-8d3a-8b8239f6625e.png)

**Comment by technicalpickles** [comment]
Just checked and it's 80.0 with an update waiting...

_upgrading intensifies_

80.0.1, and the same impact.

Just recalled I had this extension though 😬 

![image](https://user-images.githubusercontent.com/159/92418136-fa1c3480-f133-11ea-9d89-0057e077dd17.png)

Turning off leak protection fixes it. This is the plugin: https://addons.mozilla.org/en-US/firefox/addon/webrtc-control/ I'm updating the title to reflect that.

So, I think to safe to say this is an edge case for not many users. It may be worth programatically making sure webrtc is able to be initialized though, for code hygiene.

**Comment by RPDeshaies** [comment]
Yeah I think that if the user disabled WEB RTC, I should probably show a message explaining what is wrong!

Thanks for helping me troubleshoot and updating the issue

**Comment by Erynus** [comment]
One of my players have this problem since several weeks ago. I think it have something to do with her ISP because on occassion she can join a game, but if she gets disconnected she became unable to join with any browser , even on a new game. 
It shows up the message "WebRTC: ICE failed, your TURN server appears to be broken, see about:webrtc for more details" on firefox console. At first she could connect by cable, but after a few days she can't do it neither by cable nor by wifi.
If she host a game, everyone else can join without problem, but no other way around.
All Webrtc tests i ran was ok, so i don't know what the problem can be. We can video-chat and even connect to her computer remotelly, but connecting to a game is a no-no and show only the spining circle.
