### ISSUE TITLE
Templates are not saved

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari#140]
## 🚩 Describe the bug

After modifying characters sheet, pressing save, there is confirmation of save, but reloading same template all changes are lost.

## 🔢 Steps to reproduce

1. https://fari.app/
2. Click characters
3. Click New
4. Toggle Advanced Mode
5. Modify Sheet (eg, add stress track)
6. Press Save
7. Press Load Template
...

## 🟢 Expected behavior

When saving a modification of a template, I expect to get modification back after loading.
[Or the appearance of a new custom_named template that contains the modifications]

## 🔴 Actual behavior

All modifications are lost.

**Comment by RPDeshaies** [comment]
Hey! 

So this is not _really_ a bug since templates are hard coded in the app and cannot be modified by the users.

* Do you users should be able to create their own reusable templates ? If so, why do you think it would be useful ?
* Do you think I should add more default templates in there instead of giving users the ability to create their own ? If so, which templates do you think I should add ?

https://github.com/fariapp/fari/blob/8cb46697d2af1ac6e04679d45eea67881d4d322d/lib/contexts/CharactersContext/CharactersContext.tsx#L308-L312

**Comment by SpaceDiceMan** [comment]
> So this is not really a bug since templates are hard coded in the app and cannot be modified by the users.

But there is a save button on that page?

> Do you users should be able to create their own reusable templates ? If so, why do you think it would be useful ?

Yes, because various FATE games use slightly different rules and add various 'boxes' of information to the sheet.

> Do you think I should add more default templates in there instead of giving users the ability to create their own ? If so, which templates do you think I should add ?

Having the save button work or a download/upload/save+link option, so that all players have access to same template created by GM, is already great first step.
Missing templates: Tachyon Squadron (offical Evil Hat product) and the various FATE worlds.

**Comment by RPDeshaies** [comment]
> But there is a save button on that page?

Which saves your character sheet, not the template

> Yes, because various FATE games use slightly different rules and add various 'boxes' of information to the sheet.

Which you can still do, but only on your character sheet, not templates

**Comment by SpaceDiceMan** [comment]
Then indeed it's not a bug, but my misunderstanding of the save button. Then I will make a feature request for the option for the GM to share a modified template with his players (which might already exist).
