### ISSUE TITLE
Pinned Cards are Duplicated on Load

### ISSUE THREAD

**Issue by NoahEFaust** [fariapp/fari#305]
When loading a scene, cards that are pinned create a duplicate copy of themselves.

Browser: Firefox
Desktop version

Reproduction steps:
1. Create a new scene and add a card.
2. Pin the card and save the scene
3. Click the overflow menu icon and select "Load"
4. Select the scene that was just saved
Observed: There are now two identical copies of the pinned card
Expected: The scene remains unchanged when loading

**Comment by RPDeshaies** [comment]
This is actually a feature! (if I understand your steps to reproduce correctly)

Pinned cards are what I would call "sticky"

So when you reset or load a different scene, pinned cards are going to be copied from the scene you were looking at to the new scene you are loading.

They are used so that you can have NPCs or aspects stick from one scene to another.

If I misunderstood your issue though, don't hesitate to correct me !

**Comment by NoahEFaust** [comment]
Ah I see! I didn't realize this was intended to move cards between scenes. I thought it was just a way to make the most important ones stay at the top.
