### ISSUE TITLE
Scene Name Placeholder Text

### ISSUE THREAD

**Issue by ronrothjr** [fariapp/fari#59]
## 🚩 Describe the bug

This bug is a minor UI/UX concern regarding placeholder text for Scene Name.  Placeholder text should not be used as the label or, as in Material Design, it should float above after the user begins typing.

Rationale (see #7):
https://uxplanet.org/10-rules-for-efficient-form-design-e13dc1fb0e03

## 🔢 Steps to reproduce

1. Go to 'fari.com'
2. Click on 'Play Online Game (BETA)'
3. Click on the text box containing 'Name of your scene...'

## 🟢 Expected behavior

Placeholder text 'Name of your scene...' should disappear and the text box should present a blinking cursor with no text inside it.

## 🔴 Actual behavior

The cursor appears blinking within the placeholder text, so that the user must delete it.

## 💅 Screenshots

...
![image](https://user-images.githubusercontent.com/3952714/82740473-08764a00-9d17-11ea-81d6-3db8bf269ce5.png)

**Comment by RPDeshaies** [comment]
Hey, thanks for filling that issue.

The problem is that this "Name Of Your Scene" is not a placeholder but the "default value" of a scene.

And I agree, not a fan of placeholders myself.

I think it would make more sense to get rid of that and probably just focus the cursor of the user inside that box (like for aspects) on load.

I will update the code for v2.2.3!
