### ISSUE TITLE
Add character sheet elements to player characters

### ISSUE THREAD

**Issue by ConDar15** [fariapp/fari#61]
## ✅ Describe the solution you'd like

The character tracker currently has names, initiative, fatepoints and dice, but it would be useful to the user to have other elements accessible as well. In particular I think that (as a collapsible area) players and GMs should have access to:

- Stress
- Consequences
- Skills with a dice roller (e.g. if they had a +2 skill they could roll the dice and automatically get the result + 2)
- A place for Aspects and Stunts, though this is more of a nice to have as it isn't something regularly changing.

There would be benefit to adding such elements (particularly skills) to npcs/bad guys

## ✏️ Describe alternatives you've considered

This would be best implemented as a collapsible section so that if people don't want to use the more extensive features it doesn't need to be seen/interacted with to still have a good experience.

## 📄 Additional context

Requested by several users on the Fate RPG subreddit: [comment requesting the feature](https://www.reddit.com/r/FATErpg/comments/go488g/fari_220_player_controls_confetti_and_dark_theme/frex803?utm_source=share&utm_medium=web2x)

**Comment by RPDeshaies** [comment]
I agree character sheets seem to be one of the most popular features requested by people using Fari.

I started working on them and the way I envision them to work is that people will have a screen for "adding and editing characters" outside of a scene. It will be a separate page.

When joining a session, the list of all characters created by that user will be displayed and instead of picking a "name", you could click on a character you created in advance instead.

For character sheets, because Fate is not like DnD where everything is very "Strict" and "by the book" (most of the time*) and people often hack Fate, Character Sheets need to reflect that.

For that reason, every single property in the character sheet will be editable.

You will be able to have

* N aspects
* N stress tracks (and rename them)
* N consequences (and rename them)
* N Stunts and Extras (and rename them)
* N Skills (and rename them)

Where N can be from `0 to Unlimited` (theoretically)

When a player joins a session with his character sheet, everyone will be able to click on the "player row" to open the character sheet.

Here's a preview of the character sheet I'm working on, based off the new [condensed sheet](https://www.evilhat.com/home/wp-content/uploads/2013/02/Fate-Condensed-Character-Sheet.pdf)

Feedback is welcomed!

![image](https://user-images.githubusercontent.com/6224111/82759811-960c7500-9dbd-11ea-8439-f2d25f608d4a.png)

**Comment by ConDar15** [comment]
Two queries that may inform development:
1. How will these character sheets be stored? Local storage, external database with login, etc...
1. Will it still be possible to join in the current drop in manner? I feel the current system is great as is, and if it's possible to keep that while also adding this functionality this would be great.

**Comment by RPDeshaies** [comment]
1. Yes it will be using local storage (for now)
2. Yeah it will. I'm planning on keeping the current way of joining a session

Basically, when joining a session, you will be prompted to enter a character name OR select an already available character (that was created in advance)
