### ISSUE TITLE
Add support for self-hosting via Docker

### ISSUE THREAD

**Issue by amatriain** [fariapp/fari#67]
These days a lot of software is distributed in the form of Docker containers, which vastly simplifies deploymend and self-hosting.

It would be nice if this project included an official Docker image, accessible from hub.docker.com.

**Comment by RPDeshaies** [comment]
Hey @amatriain,

So, Fari was not made to be "self-hosted" really since it's not really a server  but more an "open source / free service"

But to understand more your request, could you expand more on why you would want this?

Also, next time you open an issue, don't hesitate to use the available issue template has it helps me triage them more easily! 

Thanks!

**Comment by amatriain** [comment]
The code is distributed with a GPL3 license, that means people can get it and deploy it in their own machines, either for development purposes or to use their own deployment in their Fate games instead of accessing https://fari.app (there's a lot of reasons some people prefer self-hosting open source software instead of accessing it through a SaaS deployment like https://fari.app ).

The currently supported way of deploying Fari in a machine is via npm and yarn. This results in Fari being installed along OS packages and other host sofware. That has security implications and somewhat complicates management and eventual removal of Fari from the machine. 

These days most people prefer deploying software like this in the form of Docker containers, even for local development purposes. Docker makes deploying and undeploying a breeze, isolates the software from the rest of the host machine and makes updates easier (just download a new Docker image version and recreate the container using the new image).

I just wanted to ask if you would consider creating an official Docker image for the project. Anyone can create a Docker image from the repo and publish it in hub.docker.com , of course, but an official one would get more traction.

**Comment by RPDeshaies** [comment]
Just an FYI that https://fari.app does not store any information in a database or something like that. Everything is in RAM or stored in the local storage of your computer.

> there's a lot of reasons some people prefer self-hosting open source software
Considering that, I'm curious what are those reasons.

There is an effort at managing a docker image and I want to make sure the effort is worth it. 

Fari doesn't even have an express server or something like that because it relies on Netlify to run in the cloud and ParcelJS to run locally. 

> The currently supported way of deploying Fari in a machine is via npm and yarn.

This should _normally_ be used for development purposes only.

> These days most people prefer deploying software like this in the form of Docker containers, even for local development purposes.

Those are IMHO personal preferences. 

https://fari.app is itself not deployed using docker because it relies on Netlify to distribute the app easily across the world relying on its CDNs because there is no backend server for Fari.

Using Netlify and it's CDN gives me the ability to distribute the app at no cost because Netlify has been very generous at giving me a generous open-source plan for Fari.

> Docker makes deploying and undeploying a breeze, isolates the software from the rest of the host machine and makes updates easier 

On that, I agree! Docker is fantastic but I'm not sure how many people would actually deploy their own instance of Fari since it's not really _made for that_.

If this issue gets more traction I will consider it. 

For now, I'll keep it on hold or work on it if I have some downtime and want to do it just for fun 😉

**Comment by RPDeshaies** [comment]
Will close the issue for now and will re-open if it gets more traction! Thanks

**Comment by Nachtschwingeswildhunt** [comment]
Opening this again because I feel I am one of those sources of "traction". In my case, I want to have control over all the data, and I have the server. I get if creating and maintaining a docker image is lots of work but if the only argument is that "not many people would use it" I beg to differ. Being able to selfhost things like this via dokcer would open up fari to a lot more people.

**Comment by lynn0702** [comment]
I want to reiterate, unequivocally, that fari does not have your data. Your scenes, characters, card collections, etc only exist in your browser in localstorage. There is no fari storage server.
