### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by kamilmlodzikowski** [fariapp/fari#75]
## 🚩 Describe the bug
My players cannot connect to my game and I cannot connect to one created by any of them (the rest is able to).

## 💅 Screenshots

...
![image](https://user-images.githubusercontent.com/28903797/83773715-2cc21700-a685-11ea-8132-3297adb43d5f.png)

## 🖥 Desktop or Smartphone

- OS: Ubuntu 18.04 and Win10
- Browser: chrome and firefox
- Device: Dell Laptop

**Comment by RPDeshaies** [comment]
Hey @kamilmlodzikowski, 

Can you try testing again but opening the browser's dev console before trying to join a game and copying the error displayed in there if there is any.

How to open the dev console: https://developers.google.com/web/tools/chrome-devtools/open

---

Fari's peer servers are up and running and they are doing just fine (just tested them) so my guess is that you are part of an unlucky group of users affected by a browser peer-to-peer limitation about symmetric NATs.

From [PeerJS's documentation](https://peerjs.com/docs.html#start)

> Are there any caveats?
> 
> A small percentage of users are behind symmetric NATs. When two symmetric NAT users try to connect to each other, NAT traversal is impossible and no connection can be made. A workaround is to proxy through the connection through a TURN server. The PeerServer cloud service provides a free TURN server. This will allow your PeerJS app to work seamlessly for this situation

I am currently not hosting a TURN server for Fari and the free one provided by PeerJS is always down so that's not an option.

For now, I would suggest using Fari's offline mode while screen sharing your browser.

I understand that is not ideal and I'm sorry for the inconvenience it's causing.

**Comment by kamilmlodzikowski** [comment]
Thank you for response.
This is my log from dev console:

> 4f5b9110-7f56-4acb-8826-81aa261a070f:1 A cookie associated with a cross-site resource at http://ko-fi.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
> instrument.ts:129 usePeerJS: Setup
> instrument.ts:129 usePeerJS: Setup
> instrument.ts:129 PeerJS:  Socket open
> instrument.ts:129 PeerJS:  Server message received: Object
> instrument.ts:129 usePeerJS: Connection Opened
> instrument.ts:129 PeerJS:  Socket open
> instrument.ts:129 PeerJS:  Server message received: Object
> instrument.ts:129 usePeerJS: Connection Opened
> instrument.ts:129 Connection: Setup
> instrument.ts:129 PeerJS:  Creating RTCPeerConnection.
> instrument.ts:129 PeerJS:  Listening for ICE candidates.
> instrument.ts:129 PeerJS:  Listening for data channel
> instrument.ts:129 PeerJS:  Listening for remote stream
> instrument.ts:129 PeerJS:  add connection data:dc_8bfn650gukm to peerId:4f5b9110-7f56-4acb-8826-81aa261a070f
> instrument.ts:129 PeerJS:  Created offer.
> instrument.ts:129 PeerJS:  Set localDescription: RTCSessionDescription {type: "offer", sdp: "v=0
> ↵o=- 1336888203198236211 2 IN IP4 127.0.0.1
> ↵s…:0
> ↵a=sctp-port:5000
> ↵a=max-message-size:262144
> ↵"} for:4f5b9110-7f56-4acb-8826-81aa261a070f
> instrument.ts:129 PeerJS:  Received ICE candidates for 4f5b9110-7f56-4acb-8826-81aa261a070f: RTCIceCandidate {candidate: "candidate:2622663921 1 udp 2113937151 c4224fc9-3f3…typ host generation 0 ufrag vAcM network-cost 999", sdpMid: "0", sdpMLineIndex: 0, foundation: "2622663921", component: "rtp", …}
> instrument.ts:129 PeerJS:  Received ICE candidates for 4f5b9110-7f56-4acb-8826-81aa261a070f: RTCIceCandidate {candidate: "candidate:842163049 1 udp 1677729535 85.221.141.25… rport 0 generation 0 ufrag vAcM network-cost 999", sdpMid: "0", sdpMLineIndex: 0, foundation: "842163049", component: "rtp", …}
> instrument.ts:129 PeerJS:  Server message received: {type: "ANSWER", src: "4f5b9110-7f56-4acb-8826-81aa261a070f", dst: "e1f5087c-b847-49be-a2ed-b8c0508deb0f", payload: {…}}
> instrument.ts:129 PeerJS:  Setting remote description RTCSessionDescription {type: "answer", sdp: "v=0
> ↵o=- 2300143649983229288 2 IN IP4 127.0.0.1
> ↵s…:0
> ↵a=sctp-port:5000
> ↵a=max-message-size:262144
> ↵"}
> instrument.ts:129 PeerJS:  Server message received: {type: "CANDIDATE", src: "4f5b9110-7f56-4acb-8826-81aa261a070f", dst: "e1f5087c-b847-49be-a2ed-b8c0508deb0f", payload: {…}}
> instrument.ts:129 PeerJS:  handleCandidate: {candidate: "candidate:2109127427 1 udp 2113937151 100.69.226.1…typ host generation 0 ufrag nuT2 network-cost 999", sdpMid: "0", sdpMLineIndex: 0}
> instrument.ts:129 PeerJS:  Added ICE candidate for:4f5b9110-7f56-4acb-8826-81aa261a070f
> instrument.ts:129 PeerJS:  Set remoteDescription:ANSWER for:4f5b9110-7f56-4acb-8826-81aa261a070f
> instrument.ts:129 PeerJS:  Server message received: {type: "CANDIDATE", src: "4f5b9110-7f56-4acb-8826-81aa261a070f", dst: "e1f5087c-b847-49be-a2ed-b8c0508deb0f", payload: {…}}dst: "e1f5087c-b847-49be-a2ed-b8c0508deb0f"payload: {candidate: {…}, type: "data", connectionId: "dc_8bfn650gukm"}src: "4f5b9110-7f56-4acb-8826-81aa261a070f"type: "CANDIDATE"__proto__: Object
> instrument.ts:129 PeerJS:  handleCandidate: {candidate: "candidate:842163049 1 udp 1677729535 31.0.66.36 65…rt 45752 generation 0 ufrag nuT2 network-cost 999", sdpMid: "0", sdpMLineIndex: 0}
> instrument.ts:129 PeerJS:  Added ICE candidate for:4f5b9110-7f56-4acb-8826-81aa261a070f
> instrument.ts:129 PeerJS:  iceConnectionState is disconnected, closing connections to 4f5b9110-7f56-4acb-8826-81aa261a070f
> instrument.ts:129 PeerJS:  Cleaning up PeerConnection to 4f5b9110-7f56-4acb-8826-81aa261a070f

**Comment by RPDeshaies** [comment]
Hey! I was wondering if you were still experiencing the issue?

If so, might I suggest you try with a different device and internet connection (perhaps on your phone with LTE or with a laptop using a friend's wifi connection)

Will close the issue for now except if you can help me find some sort of steps to reproduce because for now, it seems like an isolated issue.

Sadly the logs you provided doesn't indicate anything I could fix from my end but it seems to point towards an issue with the way your Internet service provider is configured
