### ISSUE TITLE
Copying and sharing characters

### ISSUE THREAD

**Issue by beijolo** [fariapp/fari#82]
Thank you very much for Fari, it's awesome. I have a suggestion: it would be very useful if the GM (or anyone, really) could create, copy and share characters with the players, and vice-versa. I have a custom sheet for my game and it would be easier if I could create a character in Fari as an "empty template", so I could make copies, fill them differently for each character, and then share with my players - maybe by permitting the GM to add the already created/filled characters to the session and attributing them specifically to players? I don't know a thing about programming, so is more of a "user experience" feedback. Hopefully there is a feasible solution for it. Thanks a lot for all the effort!

**Comment by RPDeshaies** [comment]
Hey! Thanks for submitting this issue.

I agree that this would be a pretty great feature to have. The only issue is that because I don't have any backend server or database which would simplify the way of handling this.

I can only share things using peer-to-peer communications or via URL parameters (and those have a pretty low limit of characters which makes sharing big JSON objects like characters sheets relatively impossible)

So sadly I don't have a perfect solution for you yet.

What I would do for now would be to ask your players to create a "Custom Character"

![image](https://user-images.githubusercontent.com/6224111/86631578-5039f380-bf9c-11ea-8354-1a7d0cd0643d.png)

And then, join a session. As a GM, you have total control over their character sheet and from there you can modify them as you please and when you save, the players will receive the modifications.

It's not ideal, I understand :/

To be transparent with you, hosting a server, a database, handling user management (login and whatnot) has a cost that I'm not willing to pay considering Fari is a free product.

If you have any suggestions though on a solution I might have missed don't hesitate~

**Comment by beijolo** [comment]
Oh, I did not know I could do that. It's a good enough solution :)
Thank your for the clarity of your explanation, I understood it. And thank you for freely providing us with Fari! It's my favorite online tool for playing Fate during quarantine, and that's important to me and my friends. Wish you health and success!

**Comment by RPDeshaies** [comment]
Happy this works out for you! :D

Thanks for using Fari! I'm so happy to hear comments like those
