### ISSUE TITLE
As a GM, I want to have more options when using the drawing tool

### ISSUE THREAD

**Issue by RPDeshaies** [fariapp/fari#85]
## 🚩 Is your feature request related to a problem? Please describe

Give the GM the possibility to have a better and bigger drawing tool with the ability to create boxes, circles, change pen color

## ✅ Describe the solution you'd like

- [x] ability to draw forms (circle, rectangles, freeform)
- [x] ability to change pen color
- [x] index card "add draw area" ?
- [x] save to index card ?
- [x] add player tokens ? 
- [x] full screen for GM ?
- [x] compressed view for players ?

## ✏️ Describe alternatives you've considered

GM could also use another tool for this but it would be best if everything was within the same app

## 📄 Additional context

Coming from #84 

...

**Comment by ddkn** [comment]
Hey I was checking out Fari.app, and it seems really cool! I like the minimalist aesthetic. 

I think leaving out character images would be good idea for the drawing pad in favour of **tokens of shapes and colours** that could be moved around. Not sure how hard that is to implement, but simple shapes, pen tool, colour options and movable tokens would be the minimal ideal setup.

**Comment by RPDeshaies** [comment]
Hey! I Agree character tokens should be taken into consideration when enhancing the drawing tool! Thanks for the suggestion!

**Comment by ddkn** [comment]
Yeah no worries! I am pretty pumped to try and run using this as it seems to fit my style a lot better. But I think for my group, tokens are a bare minimum.

**Comment by RPDeshaies** [comment]
Good point! An eraser would be very cool indeed!

**Comment by player-03** [comment]
I support all of these, and I'd like to add an idea of my own.

Under the drawing canvas, add a "save as index card" button. When clicked, it creates a new index card with a non-editable copy of the canvas. This index card would also have a title field (initially blank), and the usual menu to add invokes/stress/whatever.

This isn't a high priority, but I think it would be cool for artistically-inclined GMs to be able to have multiple images onscreen at once.

**Comment by RPDeshaies** [comment]
@player-03 nice idea, I was thinking about adding an "index card menu" to "add draw area" at the bottom of the card but I like this idea because it gives you more room to create multiple drawings.

I started working on an initial proof of concept and so far it's going pretty great:

![image](https://user-images.githubusercontent.com/6224111/92959719-50da8480-f43a-11ea-8c34-7f5ba4b782f2.png)

**Comment by RPDeshaies** [comment]
Added all the suggestions in the issue's description. 

I might split this issue into multiple sub-issues since I might not be able to do all of them for v3.2.0 but I'm pretty sure I could deliver basic and pen colours as a first version

**Comment by RPDeshaies** [comment]
![example](https://gyazo.com/1f1a664a0febfb388dad21cdf09e7dcb.gif)

**Comment by player-03** [comment]
Wow, I like the variability in line weight, and the fact that the squares aren't perfectly identical.

But why are they filled when the normal lines aren't?

**Comment by RPDeshaies** [comment]
> the fact that the squares aren't perfectly identical.

I know! I love it too!

> But why are they filled when the normal lines aren't?

Don't worry too much about this ahaha I'm playing around with different settings 😅 

But yeah, once I implement a color picker, it will affect the lines and the forms.

I kinda like the black borders on the forms though so perhaps I'll keep them.

Something like:

* if you chose the color red and draw a line, the line will be red
* if you chose the color red and draw a form, the form's borders will be black but will be filled in red.
* if you don't chose a color and draw a line, the line will be black
* if you don't chose a color and draw a form, the form's borders will be black and it's content "transparent" to match the current background.

**Comment by player-03** [comment]
I agree the lines should stay, but users won't like the inconsistency of the color picker. What if I just want a red square outline, and no fill? How do I do that?

I'd start by removing all fills and seeing how it looks. (The goal isn't to create a full-featured image editor, but to encourage quick, abstract sketches.) If you still want fills, there are a couple options from there:

- Add a second color picker.
- Add a paint bucket tool for filling closed shapes. With this you'd only need one color picker, and the user could switch colors in between drawing the lines and adding the fill.
- Add a "background brush" that paints thick lines on a background layer. That way you can quickly fill in (most of) the circle/square/custom shape, while preserving the fine detail, and the fill will look organic, like all the other slightly-squiggly lines. (This one would definitely require a tooltip.)
- Something else.

**Comment by RPDeshaies** [comment]
Latest build GIF: https://gyazo.com/22bbb6d7b8e6d20928de3947390a628c

Here's a screenshot of the new color picker (the default colors in there can be changed so I'm open to suggestions): 

![image](https://user-images.githubusercontent.com/6224111/93137535-a10c4d80-f6ab-11ea-8ccc-8b9ff890afae.png)

Here's a screenshot of the "small view"

![image](https://user-images.githubusercontent.com/6224111/93137459-7f12cb00-f6ab-11ea-9a21-2c6e36ab67b0.png)

Here's a screenshot of the "fullscreen view"

![image](https://user-images.githubusercontent.com/6224111/93137489-88039c80-f6ab-11ea-930e-2bf157d15725.png)

**Comment by ddkn** [comment]
This is amazing! The full screen and the movable items! So much more fluid to move drawings, when compared to roll20. It doesn't look like a stretch to have tokens (even using circles of colour would work).

## Colours

Default fill colour? I would say one of the "blues". Since the books are blue, or use one that is the default colour of Fari. Or do you mean default palette? 

If colour palette choices were an option, I would choose a **colour blind** friendly palette like this [one](https://www.nature.com/articles/nmeth.1618) (backed by science!). [Here](https://davidmathlogic.com/colorblind/#%23000000-%23E69F00-%2356B4E9-%23009E73-%23F0E442-%230072B2-%23D55E00-%23CC79A7) the author shows how people perceive them. I actually use this for writing papers too, below is the colours (the order is just for plotting purposes for most contrast).

![image](https://user-images.githubusercontent.com/13819239/93396047-68a47500-f84d-11ea-8c37-a93012f71b1d.png)
[source](https://www.nature.com/articles/nmeth.1618)

![image](https://user-images.githubusercontent.com/13819239/93396487-27609500-f84e-11ea-83f3-cbfb48c241ed.png)
[source](https://davidmathlogic.com/colorblind/#%23000000-%23E69F00-%2356B4E9-%23009E73-%23F0E442-%230072B2-%23D55E00-%23CC79A7)

As you add more colours the more difficult it becomes to discern. I could scour around the internet for something if you needed a bit more, but as the interface is simple, I think the above would be good if you wanted to accommodate.

Later down the road for the GM you could add a palette setter if people needed it. Like if they wanted to do: Fate of Chuthlu or something.

## Idea for Tokens
Perhaps have it so when you drag a player name onto the drawing area it creates a hexagon/octagon/circle, with their initials of their character or "token initials" set in the character sheet? Future stuff, haha.

Amazing work!

**Comment by RPDeshaies** [comment]
A color friendly color palette is a really good idea! thanks for the suggestion.

I played around with saving the drawing area to an index card and was able to make it without too much effort but since index cards are saved in a scene, I really want to be 100% sure about the "data model" before enabling this feature.

So for now, the drawing area will stay ephemeral and you won't be able to add it to an index card but the code is there and ready to be turned on. 

For player tokens, I'll have to think about it. Dragging a player name might be a good idea but might not be very clear or intuitive.

I thought about perhaps a button that "creates one token with a player's initial, per player" but since this drawing area is using an SVG element, I'll need to learn how to draw a circle with text in it (which I'm not very familiar with 😅 )

Stay tuned

**Comment by ddkn** [comment]
Yeah, the data being stored on the server could rack up, luckily svg's are small. But even for now these improvements are gold. I agree with saving that for another update, once you know better. Perhaps have a limit of vertices, or svg size would help there.

True, clicking and dragging isn't too clear and separate from the drawing area. 

A token button or icon is more intuitive. If text is an issue, maybe an array of symbols to select would work. Then use the  colour picker. Some symbols as an off hand idea: cross, plus, diamond, star, dot, multiple dots, scratches. Here is a quick example I made.

![image](https://user-images.githubusercontent.com/13819239/93469711-40f1f300-f8c7-11ea-8d45-fe806bed4107.png)

But they would look cool with your *hand drawn* style you have chosen for the drawing area, especially for *scratches*. It is just a quick suggestion, there are probably better ideas, maybe text isn't too bad. However, icon selecting is much quicker for gameplay flow reasons.

**Comment by RPDeshaies** [comment]
Did you draw those yourself? If so, they look very nice!

I think they would fit even if they don't feel like hand-drawn...

What I like about Fari is the fact that it mimics real-life interactions (like sketching text on index card) but at a real table, players might still be using "real physical tokens or figurines" to represent themselves in zones.

I could perhaps add a dropdown with numbers in it and a button to add `n` badge (where `n` is the value of the dropdown with a max of 6-8 badge ?) and each badge added to the drawing area is a different badge like the one you included above.

What I'm wondering is, would you be interested in designing perhaps 5 more badges (to have a total of 8), I could then include them in the app as part of this feature? It would be pretty cool I think!

If you are interested: 

* make sure they are exported as SVGs
* make sure the SVGs have the same width/height
* just be mindful of the [license of this project](https://choosealicense.com/licenses/agpl-3.0/) (Contributors provide an express grant of patent rights)

**Comment by RPDeshaies** [comment]
Here's a proof of concept I have with player token management and colour blind friendly colours: 

https://gyazo.com/69dd0f137c13f9dc8ec6dc01ba915d03

**Comment by ddkn** [comment]
Oh awesome!

Yeah I did make those, they took about 2 minutes total. I just use inkscape for vector (svg) art. I can easily make the badges for you  (I am just at work right now and will be home in about 4 hours). Do you have any design considerations for the badges?

That is,
* Outside shape: Octagon/Hexagon?
* 6-8 distinct symbols?
* Should I include fill colours? Or leave them as white? for the pieces.
* One giant file or a series of separate files?

I can make some drafts of a series of symbols and shapes and you can approve what you want. As for license since it is a art, it should *technically* fall under a [Creative Commons - ShareAlike license (CC-BY-SA)](https://creativecommons.org/licenses/by-sa/4.0/). But if it makes sense to license art as AGPL, then go ahead. Which could be added in an assets folder and licensed as is. I don't think it should conflict with AGPL, since it is *effectively* the GPL but for art. 

I did a bit of searching and there is [this](https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/), which shows that CC-BY-SA can turn into a GPL work when copied and worked on, but not back. So I can give the original artwork as CC-BY-SA and all should be good!

**Comment by RPDeshaies** [comment]
I think

* Octagons are nice but what do you think looks better?
* 8 different symbols would be nice (since I have 8 different colour blind-friendly colours)
* For the fill colours, you can leave the borders and symbols black and the background white. I'll modify them on the fly programmatically. 
* separate files, please!

Thanks for all this research about licenses :)!

**Comment by ddkn** [comment]
* I can send you a few sets of 8 token shapes and you pick the one you like! What is the size restraints (1cm or whatever in pixels or ems)
* 8 sound great!
* I will post a draft up here of all the sets so you can review, pick and choose (or have options for later)

The rest is easy peasy on my end. I will work on these tonight.

**Comment by RPDeshaies** [comment]
No rush but thank you so much!

As for the size, Material UI (the framework I'm using) uses a view box of 24px by 24px, so lets try to aim for that

```
viewBox="0 0 24 24"
```

**Comment by player-03** [comment]
I'd vote for the hand-drawn style if possible.

As for symbols, I really like the cross and the plus. Both are abstract and widely useful. And since these shapes fit well in octagons, I'd stick with octagons for now.

Other ideas:
- A lightning bolt. Pros: represents a range of useful concepts like "high speed," "technology," or "stunned." Cons: none?
- A raindrop. Pros: flexible. Depending on what color you pick it can represent a variety of liquids, and liquids fill a variety of roles. Cons: not very useful as a token for a PC.
- An eye. Pros: represents a few useful concepts, like "attentiveness," "knowledge," or even "blindness." Useful as the token for whichever PC has highest Notice. Cons: not very abstract.
- [Wavy lines](https://game-icons.net/1x1/lorc/heat-haze.html) as a substitute for scratches. Pros: does a better job of representing fire, flowing water, or smoke. Cons: does a worse job at representing scratches, rows, or roads.
- A question mark. Pros: the most expressive punctuation mark out there. Cons: might feel out of place since there's no other punctuation.

**Comment by RPDeshaies** [comment]
@player-03 just an FYI that I'm not looking at creating a versatile generic token tool but an easy way to drop the "players" on the drawing pad.

Here's an example of the player token tool

![](https://i.gyazo.com/cc8cb9b24461cc903d36c2a2bc1411ef.gif)

**Comment by player-03** [comment]
Yeah, that's why I tried to keep it abstract. But I guess I need to recalibrate how abstract.

Ok, here are some new suggestions, aiming to minimize symbolism and maximize distinctiveness. Also avoiding anything that's a rotated version of anything else.

![Preview](https://user-images.githubusercontent.com/433823/93530817-3574eb00-f90c-11ea-8523-5114bc7467b5.png)

[Fari icons v2 CC-BY-SA.zip](https://github.com/fariapp/fari/files/5241988/Fari.icons.v2.CC-BY-SA.zip)

**Comment by ddkn** [comment]
Here they are,

Sorry, I was eating supper. So I have a few designs ideas:

**No border, white icon**
![image](https://user-images.githubusercontent.com/13819239/93534178-f39f7100-f91a-11ea-9075-ed571015da98.png)
![image](https://user-images.githubusercontent.com/13819239/93536208-e1bfcd00-f91e-11ea-8a6e-e44617db14f1.png)

**No border, black icon**
![image](https://user-images.githubusercontent.com/13819239/93534240-16ca2080-f91b-11ea-8a6e-b4e0938e36aa.png)
![image](https://user-images.githubusercontent.com/13819239/93536261-fdc36e80-f91e-11ea-8f9c-9fdb5c123083.png)

**Border, black icon**
![image](https://user-images.githubusercontent.com/13819239/93534424-6f012280-f91b-11ea-8c64-26ef905c8332.png)

**No border, white Icon, rotated**
![image](https://user-images.githubusercontent.com/13819239/93535369-32362b00-f91d-11ea-8a5f-b1e7f5239749.png)

I personally like the *no border, white icon(s)*, either rotated or non-rotated. The non-rotated will have an extra two pixels of colours, (about 2 is lost in the rotation, but visually neat). Overall the hexagons will be better for rendering I think, and no corner case for black icons, since the inside needs to be inverted.

@player-03 Those look nice! I realized after that the + sign was a bad idea (because it is Fate, haha). 

So @RPDeshaies  you can pick which one you want and I will make a zip file for you. I will make it so the first item down is the octagon, so it should be consistent in the svg file.

**Comment by ddkn** [comment]
Actually here is one set of icons for you to play with or try out:
[fari.app-token-set.zip](https://github.com/fariapp/fari/files/5242421/fari.app-token-set.zip)

And a 100% scaled image
![image](https://user-images.githubusercontent.com/13819239/93537927-32d1c000-f923-11ea-86de-f4c5f2de5802.png)

**Comment by ddkn** [comment]
Here is the border tokens, just in case this was easier for you or more appealing:
[fari.app-token-set-border.zip](https://github.com/fariapp/fari/files/5242759/fari.app-token-set-border.zip)

And a image at 100%
![image](https://user-images.githubusercontent.com/13819239/93543981-44bb5f00-f933-11ea-81a2-349b574e80b1.png)

**Comment by RPDeshaies** [comment]
I'll try to integrate them tomorrow morning! 
I kinda a prefer colored one but we will see. Thank you so much for this, can't wait to try it out

**Comment by ddkn** [comment]
Awesome, I am just assuming you are able to change the fill of the octagon in code somehow. I thought about it after and maybe the borders make sense, because if you move a token into a square of a colour it becomes harder to find?

Anyway can't wait to see what you come up with! I think that is enough from me, from the peanut gallery of suggestions, haha.

**Comment by ddkn** [comment]
Oh you can omit one of the tokens (like the three dots or three scratches), then when you populate you won't get a repeating combination of colour and token for quite a while. There was some pattern, the edges, they do sort of count 1-5, but the last two are just visually different.

**Comment by RPDeshaies** [comment]
Ok so I used the following icons

![image](https://user-images.githubusercontent.com/6224111/93604037-d6a68480-f992-11ea-8637-521e083fb565.png)

I colour them programmatically switching the colour every time a new token is placed on the drawing pad.

I see your point though, having a set of icons that represent  "numbers" is very nice! The thing is, I configured 8 accessible colours so that's why I think 8 different icons might be good.

So instead of removing one icon, do you think we could replace the "three slashes" or "three dots" with a more random form that does not represent a number?

That way, we could have numbers going from 1-5 and then 3 random forms.

Here's what I have so far and I think it looks very cool 😄 

![image](https://user-images.githubusercontent.com/6224111/93604715-bf1bcb80-f993-11ea-96fa-fcedf7e17dc2.png)

**Comment by ddkn** [comment]
Sorry, I was out all day. Very cool! Neat to see them in action, haha.

Well I am glad you like them and want to use them! I like your choice of the icons changing colour, much easier to program than handling corner cases.

> do you think we could replace the "three slashes" or "three dots" with a more random form that does not represent a number?

I was thinking about that last night, I did one better, homage to the coding languages that index from zero! Added a new icon too, the "gem" or six corners, now you can have 9 ([0-8].svg labelled). 
![image](https://user-images.githubusercontent.com/13819239/93655383-56673a00-f9f9-11ea-9a3a-17c9df756bfb.png)

You now have the option of having 8 colours and 9 tokens, and shouldn't see a repeating combination of token and colour for 72 tokens (overkill), so the option is there for you, if you choose to take it, in case people have more than 8 players  (baddies included)

Here is the goods:
[fari.app-token-set-border-v2.0.zip](https://github.com/fariapp/fari/files/5248874/fari.app-token-set-border-v2.0.zip)

A scratch page is a nice addition, something that keeps the map clean but still functional.

**Comment by RPDeshaies** [comment]
Awesome, I'll integrate them probably this weekend. Thanks for this!

**Comment by RPDeshaies** [comment]
I had a bit of time today during lunch

![image](https://user-images.githubusercontent.com/6224111/94065181-c8080500-fdb8-11ea-957e-9c6a7242e57c.png)

**Comment by RPDeshaies** [comment]
demo url: https://5f6bd65f61873f00ad672c79--fari.netlify.app/

might be unstable ☝️

**Comment by ddkn** [comment]
Awesome! Sorry I was out and about. The interface is nice and simple, easy to move and delete things. I really like how lightweight and simple it is. The hand drawn lines on square and circle are a nice detail!

Comments/Debugging
1. I had one case where I created a circle, then clicked delete, then when I clicked somewhere to delete a different item, the circle changed shape into an oval. Not sure if it was my browser or a glitch?

    I realize this is because the last created Rectangle/Circle, the cursor allows you to change the shape until you create a new item or delete an item.
2. I see you added a new colour (total 9)! Was that intentional or did you skip over the darker reddish/orange colour? It is skipped when tokens are placed, instead black is used twice.
3. So you creating only 9 unique tokens? No plans for having the colours alternate so that the second set (lets say the square with the line through) would be orange, instead of black? Just good to know the expected use or limitations.
4. I tried connecting as a player and it crashed, so I couldn't check what the player has access to when logging in (I did it twice and happened twice).

Otherwise this is really cool! and fun to play with.

**Comment by RPDeshaies** [comment]
1. yeah there's a bug with the delete button I need to look into it
2. yeah I was playing around with more colors but I might end up just keeping the 8 and make them repeat for tokens(except if you have a better idea)
3. yeah that's the plan but nothing is set in stone
4. also experienced this issue (I was sending the "whole component" over the network instead of sending the type of token which made the peer connection crashed because it didn't like me sending code and symbols ahaha)

**Comment by RPDeshaies** [comment]
Thanks a lot for testing this feature BTW @ddkn

**Comment by RPDeshaies** [comment]
I've made some changes to the colour palette. 
It will now have 8 accessible colours to pick from but the colours for the tokens will be as follows.


The latest preview is available here: https://5f7620594be8649c6e276b3b--fari.netlify.app/
BTW the "delete button bug is still present"


Perhaps my next step will be to try to incorporate "bad guys" in all of this... perhaps just red circles can do the trick for now...

```
export const colorBlindFriendlyColorsForTokens = [
  "#000000",
  "#e69f00",
  "#56b4e9",
  "#019e73",
  "#f0e442",
  "#0072b2",
  "#d55e01",
  "#cc79a7",
  "#EB144C",
];
```

**Comment by RPDeshaies** [comment]
New preview available with the delete button bug fixed and I also fixed a bug where I was not using all 9 available tokens

https://5f7622c0cc8a58946714a5d6--fari.netlify.app/

**Comment by ddkn** [comment]
Hey sorry, busy week!

I forgot to check out the full screen feature which is really nice! I literally got distracted just playing with the interface.

> 2. yeah I was playing around with more colors but I might end up just keeping the 8 and make them repeat for tokens(except if you have a better idea)

I am not sure if you have tried it, but you could try having the 9 tokens, but when the upside down triangle is placed as black, the next [|] could be orange, and continue that pattern. That could fix your need to create new enemy tokens, as you would have access to 72 tokens (symbol and colour) before the pattern repeats. I would *assume* that the GM would place character tokens first, but could move them around after.

I am not familiar in javascript, but effectively:

```
...
place_next_token(colorBlindFriendlyColorsForTokens[i % n_colours]);
i += 1;
...
// however events are trapped
if (screen_clear) {
    i = 0;
    ...
}
```
Assuming javascript has the modulous operator, `%`, so only the remainder is returned, i.e,
* 8%8 -> 0
* 17%8 -> 1.

It might not be a great idea, but something to try. I was just thinking along the lines of less is more, or a less busy interface and people can be as creative as they need, I think the only thing with the baddies tokens, is if there was a need to differentiate the baddies for story reasons, the above solution can encompass that (maybe circles and the GM can optionally change the colour of a token if desired). End of the day, I think whatever you choose will be great! Just trying to avoid anymore feature creep from my side, haha.

> 4. also experienced this issue (I was sending the "whole component" over the network instead of sending the type of token which made the peer connection crashed because it didn't like me sending code and symbols ahaha)

Strange, haha. FYI I am able to connect as the user. When I created things as the GM, on the users browser (just running a private browser on the same computer to connect, to keep the cookies separate), the screen/draw area wouldn't update unless I hit the maximize draw area. If I added more or moved things as the GM, the user screen still wouldn't update unless I minimized the screen from this point.

Not sure if there is a way to time stamp the last movement from the GM, and have the user interface check for last update, and update accordingly (like a 0.5s or 1s heartbeat). Or if there is a more elegant solution.

Hope this makes sense.

Pretty excited for the feature release!

**Comment by player-03** [comment]
JavaScript does support `%`, and (more to the point) I support the "72 different token combinations" idea.

**Comment by ddkn** [comment]
I suspected it did, maybe I am just too tired today, haha.

**Comment by ddkn** [comment]
Oh I forgot to mention, in your preview. I noticed when you maximize the draw area, the **pencil/pen** tool gets reselected, so If you were using the **move** tool, then maximized, it changes the **tool* to the pen, and vice versa. It might be good to keep it in it's current selection. What do you think?

**Comment by RPDeshaies** [comment]
@ddkn love the modulous approach. Clever yet simple

![image](https://user-images.githubusercontent.com/6224111/95131340-e01e4380-072b-11eb-887a-8ab99f531fc3.png)

> Not sure if there is a way to time stamp the last movement from the GM

That's already what it does. When I update the drawing pad, I "throttle" for 500ms before updating the scene for players.

On my end I see the player's screen update upon something being drawn but it does not always update when something is moved. I'll have to investigate.

Do you have the same type of behavior on your end (not syncing when moving) or do you have sync issues when drawing as well ?

**Comment by RPDeshaies** [comment]
@ddkn found the issue with player screens not being synced properly 

I was only overriding the local state of the drawing pad if the number of objects changed. 
Like if something was added or removed.

But when moving an object, the number of objects doesn't change.

For players (in readonly mode), I should always update the local state.

Thanks for testing this feature, it's really appreciated and will make the app a better product down the road.

![image](https://user-images.githubusercontent.com/6224111/95132171-54a5b200-072d-11eb-8697-9d6a90fcd9e2.png)

**Comment by ddkn** [comment]
@RPDeshaies something I picked up in embedded design. Especially when you are trying to save as many corners as possible with space.

How do you feel about the icons? Do you think/feel it is a good fit?

Testing is important, glad you found it! Pretty subtle error!

**Comment by RPDeshaies** [comment]
So thanks a lot @ddkn and @player-03 for your input and your help :) !!!

I'll close this issue for now as I think we have a fantastic MVP.

If you have other comments for v3.2.0, headover to https://github.com/fariapp/fari/discussions/123
