### ISSUE TITLE
Ability to remove elements from a card

### ISSUE THREAD

**Issue by nottsknight** [fariapp/fari#88]
## 🚩 Is your feature request related to a problem? Please describe

It's quite easy (at least if you're me) to accidentally add too many stress boxes, consequences, etc to a card.

## ✅ Describe the solution you'd like

Small (x) button next to a consequence to remove it. Small (+) and (-) at the end of stress tracks to add and remove boxes.

## ✏️ Describe alternatives you've considered

Could potentially add 'Remove' options to the card menu similar to the 'Add' options, but this would bloat the menu quite a lot.

**Comment by RPDeshaies** [comment]
Yeah, I agree. I've been wanting to do this for quite some time though I never had a good "user interface idea" on how to do it.

My basic version of fixing this issue was to add a "reset" button though it's not ideal.

But, I really like your idea of adding button at the "end of the track". I'll see what I can do for the next release!

**Comment by Erynus** [comment]
Maybe a contextual menu that opens on long click, with the Remove option for just the selected element? Just to prevent it for being deleted by mistake.

**Comment by RPDeshaies** [comment]
Here's what the new aspects card is going to look like in v3.0.0. They will look a lot more like character sheets (design and functionality wise)

![image](https://user-images.githubusercontent.com/6224111/88546121-ef756800-cfe9-11ea-971a-c862207ac171.png)

Right now I added the delete button on tracks only but I'll also add them on consequences.

fixed in #89.
Stay tuned for the release.
